### ISSUE TITLE
Need for keyboard shortcut keys to utilize both options

### ISSUE THREAD

**Issue by balayokesh** [balayokesh/speech-companion#1]
# Need for a keyboard shortcut 

## Example:
1. Pressing M should trigger Mic on and off options
2. Pressing S should trigger the speak option

## Solution:
Use JS eventlisteners

**Comment by adityasimant** [comment]
Assign this to me.

**Comment by balayokesh** [comment]
> Assign this to me.

@adityasimant I have assigned this issue to you.  Just make sure to create a draft pull request while working on commits.
