### ISSUE TITLE
Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by balayokesh** [balayokesh/speech-companion#6]
Need to create [CONTRIBUTING.md](https://github.blog/2012-09-17-contributing-guidelines/#:~:text=Oftentimes%20open%20source%20projects%20place,Here%20is%E2%80%A6) file in root folder of project.

**Comment by adityasimant** [comment]
Should I do it ?

**Comment by balayokesh** [comment]
> Should I do it ?

Sure, if you are willing to do it.

**Comment by balayokesh** [comment]
Just make sure to add these steps in that file:
Step 1: Create issue or comment on existing issue.
Step 2: Only start working on that PR once the issue is assigned to them.
Step 3: Create draft pull request and start working on adding commits.

**Comment by adityasimant** [comment]
Should I also add contribution section in readme which will redirect everyone to CONTRIBUTING.md ?

**Comment by balayokesh** [comment]
> 

Yes that would be good to have
